language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"
  - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

before_install:
  - sudo pip install GitPython bzr
  - sudo apt-get install bzr
  - sudo pip install cairosvg
  - sudo apt-get install wkhtmltopdf

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/grap/odoo-addons-misc.git $HOME/odoo-addons-misc -b 7.0
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
