addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  - LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="7.0" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

before_install:
  - sudo pip install GitPython bzr cairosvg pyBarcode
  - sudo apt-get install bzr wkhtmltopdf

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/grap/odoo-addons-misc.git $HOME/odoo-addons-misc -b 7.0
  - git clone https://github.com/OCA/webkit-tools.git $HOME/webkit-tools -b 7.0
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  coveralls
